version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/warehouse-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_APPLICATION_NAME: warehouse-service
      SERVER_PORT: 8081
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
